### PR TITLE
Update background image to be more fire

### PR DESCRIPTION
**Pull request by jaredplanter**
:fire::fire::fire:

### CODE REVIEW

**Comment by tielur** [comment]
not_approved

**Review by adamzaninovich — CHANGES_REQUESTED** [review]
All commit messages must be a direct quote of something tielur recently said to you in slack. Please rebase and force push.

**Review by mushfick — CHANGES_REQUESTED** [review]
I would like to only see the fire emoji replace his eyeballs.

"I hate you all so much right now" - Tielur

**Review by adamzaninovich — APPROVED** [review]
it only took 6 years... approved

**Pull request merged**
